version: "3"
services:
  hmpps-subject-access-request-api:
    build:
      context: .
    container_name: hmpps-subject-access-request-api
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - DATABASE_URL=db:5432
      - DATABASE_NAME=demo_db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres

  db:
    container_name: subject-access-request-db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - '5432:5432'
    networks:
      - db-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/dev/schema.sql:/docker-entrypoint-initdb.d/1-dev-database.sql

networks:
  hmpps:
  db-network:
