version: "3"
services:

  hmpps-sar-api:
    image: quay.io/hmpps/hmpps-subject-access-request-api:latest
    #    build:
    #      context: .
    container_name: hmpps-subject-access-request-api
    ports:
      - "8000:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev

  sar-db:
    image: postgres:17
    networks:
      - hmpps
    container_name: sar-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin_password
      - POSTGRES_USER=admin
      - POSTGRES_DB=auth-db

networks:
  hmpps: