services:
  hmpps-auth:
    base-url: https://sign-in.hmpps.service.justice.gov.uk/auth
    username: ${API_CLIENT_ID}
    password: ${API_CLIENT_SECRET}

  document-storage:
    base-url: https://document-api.hmpps.service.justice.gov.uk
