services:
  hmpps-auth:
    base-url: http://localhost:9090/auth
    username: test
    password: test

  document-storage:
    base-url: http://localhost:4040

hmpps.sqs:
  provider: localstack
  queues:
    audit:
      queueName: "audit"