hmpps:
  auth:
    url: http://localhost:9090/auth
    username: test
    password: test
  document-storage:
    url: http://localhost:4040

hmpps.sqs:
  provider: localstack
  queues:
    audit:
      queueName: ${random.uuid}