services:
  hmpps-auth:
    base-url: https://sign-in-dev.hmpps.service.justice.gov.uk/auth

  document-storage:
    base-url: https://document-api-dev.hmpps.service.justice.gov.uk/

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sar-db
    username: admin
    password: admin_password