services:
  hmpps-auth:
    base-url: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    username: ${API_CLIENT_ID}
    password: ${API_CLIENT_SECRET}

  document-storage:
    base-url: https://document-api-preprod.hmpps.service.justice.gov.uk

  env:
    SENTRY_ENV: preprod
