services:
  hmpps-auth:
    base-url: http://localhost:9090/auth

  document-storage:
    base-url: http://localhost:4040

hmpps.sqs:
  provider: localstack
  queues:
    audit:
      queueName: "audit"

spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: 'demo_dev_rw'
    password: 'dev_database_passwd'

  flyway:
    enabled: false
    locations: classpath:db/migration
