services:
  hmpps-auth:
    base-url: http://localhost:9090
    username: hmpps-integration-api-client # until we get a client seeded
    password: clientsecret

hmpps.sqs:
  provider: localstack
  queues:
    audit:
      queueName: ${random.uuid}