services:
  hmpps-auth:
    base-url: https://sign-in-dev.hmpps.service.justice.gov.uk/auth

  document-storage:
    base-url: https://document-api-dev.hmpps.service.justice.gov.uk/

hmpps.sqs:
  provider: localstack
  queues:
    audit:
      queueName: "audit"

spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: 'demo_dev_rw'
    password: 'dev_database_passwd'

  flyway:
    enabled: false
    locations: classpath:db/migration
