---
# Per environment values which override defaults in hmpps-subject-access-request-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: subject-access-request-api-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    DOCUMENT_STORAGE_URL: "https://document-api-preprod.hmpps.service.justice.gov.uk"
    EXTERNAL_USERS_API_URL: "https://external-users-api-preprod.hmpps.service.justice.gov.uk"
    NOMIS_USER_ROLES_API_URL: "https://nomis-user-roles-api-preprod.prison.service.justice.gov.uk"
    SAR_AND_DELIUS_API_URL: "https://subject-access-requests-and-delius-preprod.hmpps.service.justice.gov.uk"
    LOCATIONS_API_URL: "https://locations-inside-prison-preprod.hmpps.service.justice.gov.uk"
    NOMIS_MAPPINGS_API_URL: "https://nomis-sync-prisoner-mapping-preprod.hmpps.service.justice.gov.uk"
    APPLICATION_HEALTH_DEV_PORTAL_URL: "https://developer-portal.hmpps.service.justice.gov.uk/components/%s/environment/preprod"
    APPLICATION_APPINSIGHTS_SUBSCRIPTIONID: a5ddf257-3b21-4ba9-a28c-ab30f751b383
    APPLICATION_APPINSIGHTS_RESOURCEGROUP: nomisapi-preprod-rg
    APPLICATION_APPINSIGHTS_INSTANCENAME: nomisapi-preprod
    SENTRY_ENV: preprod

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
