---
# Per environment values which override defaults in hmpps-subject-access-request-api/values.yaml

generic-service:
  ingress:
    host: subject-access-request-api.hmpps.service.justice.gov.uk

  env:
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    DOCUMENT_STORAGE_URL: "https://document-api.hmpps.service.justice.gov.uk"
    EXTERNAL_USERS_API_URL: "https://external-users-api.hmpps.service.justice.gov.uk"
    NOMIS_USER_ROLES_API_URL: "https://nomis-user-roles-api.prison.service.justice.gov.uk"
    SAR_AND_DELIUS_API_URL: "https://subject-access-requests-and-delius.hmpps.service.justice.gov.uk"
    SENTRY_ENV: prod

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service
