---
# Per environment values which override defaults in hmpps-subject-access-request-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: subject-access-request-api-preprod.hmpps.service.justice.gov.uk

  env:
    SPRING_PROFILES_ACTIVE: preprod
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    HMPPS_AUTH_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
