apiVersion: batch/v1
kind: CronJob
metadata:
  name: delete-old-reports-cronjob
spec:
  schedule: "@hourly"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: delete-old-reports
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              args:
                - /bin/sh
                - -c
                - curl --retry 1 -X POST https://subject-access-request-api-dev.hmpps.service.justice.gov.uk/api/deleteOldSubjectAccessRequests